apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eprocessor-secretstore
  namespace: eprocessor
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /components/eprocessor-secrets.json
    - name: nestedSeparator
      value: ':'
